channels:
  - defaults
dependencies:
  - numpy>=1.20
  - pip>=20.3.3
  - python=3.9
  - pip:
      - matplotlib>=3.3.3
      - git+https://github.com/threeML/threeML.git@refs/pull/516/head
      - py-spi==0.9.1
      - chainconsumer
      - git+https://github.com/BjoernBiltzinger/twopc@paper_version
      - git+https://github.com/BjoernBiltzinger/pynchrotron@peaknorm
      - pandas==1.3
