name: article

on:
  push:
  workflow_dispatch:

jobs:
  showyourwork:
    runs-on: ubuntu-latest
    name: Build the article PDF
    concurrency: showyourwork-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      #- name: Set up Python
      #  uses: actions/setup-python@v2
      #  with:
      #    python-version: 3.9

      #- name: Install 3ML PR
      #  run: |
      #    pip install astromodels
      #    git clone https://github.com/threeML/threeML.git
      #    cd threeML
      #    git fetch origin pull/516/head:pr_516
      #    git checkout pr_516
      #    python setup.py install
      #    cd ..

      - name: Cache data folder
        uses: actions/cache@v2
        id: cache-data-folder
        with:
          path: ~/data
          key: data

      - name: Download data folder
        env:
          CACHE_HIT: ${{steps.cache-data-folder.outputs.cache-hit}}
        run: |
          echo "Getting data folder"
          if [[ "$CACHE_HIT" == 'true' ]]; then

          echo "data folder already in cache. using this."

          else
          echo "Download zip data folder."
          wget https://grb.mpe.mpg.de/pyspi_datafolder
          mv pyspi_datafolder ~/data.zip
          unzip -o ~/data.zip -d ~/
          fi

      - name: install dvipng
        run: |
          sudo apt-get install dvipng

      - name: Build the article PDF
        id: build
        uses: ./showyourwork/showyourwork-action
        with:
          install-tex: true
        env:
          ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}
          PYSPI: /home/runner/PySPI_data
          PYSPI_PACKAGE_DATA: /home/runner/data
