name: article

on:
  push:
  workflow_dispatch:

jobs:
  showyourwork:
    runs-on: ubuntu-latest
    name: Build the article PDF
    concurrency: showyourwork-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Cache data folder
        uses: actions/cache@v2
        id: cache-data-folder
        with:
          path: ~/data
          key: data

      - name: Download data folder
        env:
          CACHE_HIT: ${{steps.cache-data-folder.outputs.cache-hit}}
        run: |
          echo "Getting data folder"
          if [[ "$CACHE_HIT" == 'true' ]]; then

          echo "data folder already in cache. using this."

          else
          echo "Download zip data folder."
          wget https://grb.mpe.mpg.de/pyspi_datafolder
          mv pyspi_datafolder ~/data.zip
          unzip -o ~/data.zip -d ~/
          fi

      - name: Build the article PDF
        id: build
        uses: ./showyourwork/showyourwork-action
        env:
          ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}
          PYSPI: /home/runner/PySPI_data
          PYSPI_PACKAGE_DATA: /home/runner/data
